### ISSUE TITLE
We need to use Modals

### ISSUE THREAD

**Issue by reybrac** [dorrianweber/group-6-project#45]
We need to use Modals as part of our project.

A modal is a dialog box/popup window that is displayed on top of the current page:

https://www.w3schools.com/howto/howto_css_modals.asp#:~:text=A%20modal%20is%20a%20dialog,%C3%97

**Comment by dorrianweber** [comment]
I checked in with Ryan about this today in our tutoring session. We're all good on this front. That part of the assignment criteria was just saying "Hey, don't use prompt() or alert() to get info from the user or show  error messages. Make actual HTML elements instead." Which is what we're already doing.
