### ISSUE TITLE
Create quality Readme file

### ISSUE THREAD

**Issue by reybrac** [dorrianweber/group-6-project#46]
Create a quality readme file

- [x] Create initial readme file
- [x] Update with all team member info (including what each member worked on)
- [x] Add screenshot of deployed site
- [x] Fix "stretch goals" section (see comment line in readme code)
- [x] finalize

**Comment by dorrianweber** [comment]
@Jin5044  @acombs801 @caysper28 make sure you go into the readme file & add what you worked on next to your name in the "Team Members" section.
