### ISSUE TITLE
Use client-side storage to store persistent data

### ISSUE THREAD

**Issue by reybrac** [dorrianweber/group-6-project#47]
We need to store some of the data. Let's discuss how this is going to work.

**Comment by dorrianweber** [comment]
I asked Ryan about this today in our tutoring session. He said that based on our assignment, this criteria doesn't really apply to us. That bit of the rubric was basically saying that you need to use local storage if you have any relevant data to save & go back to grab later. But we do not, so we don't need to worry about this.
